name: Josh Lapham
tagline: 'Huge nerd.'
author:
  name: Josh Lapham
  email: josh@joshlapham.com
  twitter: j_lap
  github: joshlapham
shorturl: joshlapham.com
markdown: redcarpet
highlighter: pygments
timezone: Australia/Sydney
exclude: [README.md, bower.json]
safe: true
permalink: pretty
